### ISSUE TITLE
Add reminder to upgrade to 1.0.0

### ISSUE THREAD

**Issue by jbants** [stac-utils/stac-validator#132]
Add a friendly reminder to upgrade to stac version 1.0.0 for older stac versions.

**Comment by jonhealy1** [comment]
@jbants Should this wait for the 1.0.0 release or should we ask people to upgrade to 1.0.0-rc.2?

**Comment by jbants** [comment]
Let's wait for the STAC 1.0.0 release.

**Comment by jbants** [comment]
relates to #115

**Comment by gadomski** [comment]
@jbants this milestone should probably be removed/changed, yes?

**Comment by jonhealy1** [comment]
I did add this reminder to stac-check but it's not in stac-validator yet

**Comment by gadomski** [comment]
Yeah, but the milestone for this issue is 2.3.0, and we're already on 3.0.0?

**Comment by jonhealy1** [comment]
Haha true

**Comment by gadomski** [comment]
Yeah, this would just be a feature addition so it could go into a `v3.1.0`. However, I haven't looked to see whether there's been any breaking changes since `v3.0.0` that would require a major version bump, we should check that before we decide what the next milestone is.
