### ISSUE TITLE
Schema caching

### ISSUE THREAD

**Issue by tschaub** [stac-utils/stac-validator#194]
It looks like the schema caching was removed in 3e30d8287ddab91a5b9b3b5709d4ec8ce9a3ee3c (this removed the `lru_cache` decorator that was added in #41).  Would there be support for adding caching back in?

For recursive validating with many items, it would be nice to avoid fetching the item schema for each item.

**Comment by jonhealy1** [comment]
Hi. This definitely sounds like a good idea.
