### ISSUE TITLE
Cyclic dependency on `stac-check`

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stac-validator#207]
`stac-validator` depends on `stac-check` (https://github.com/stac-utils/stac-validator/blob/main/setup.py#L38) which depends on `stac-validator` (https://github.com/stac-utils/stac-check/blob/main/setup.py#L23). As I see it, there's two strategies we could use to fix this:

1. Make one of the libraries dependent on the other. E.g. `stac-check` would depend on `stac-validator`, and we would by default point people to use `stac-check` to get the full set of features.
2. Merge the two libraries into one.

**Comment by jonhealy1** [comment]
@gadomski I think option 1 is better? We could remove stac-check from stac-validator.

**Comment by gadomski** [comment]
That makes the most sense to me.
