### ISSUE TITLE
STAC 1.1 support?

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-validator#234]
It seems due to missing v1.1.0 schemas for STAC (see https://cdn.staclint.com/ ) the validator doesn't work (and as such stac-check neither) for v1.1.0.

![grafik](https://github.com/user-attachments/assets/2935daa9-7c86-4705-a669-9beb32bbdb2b)

Why is stac-validator using self-hosted schemas anyway? Can't it just load from stac-spec github directly?

**Comment by jonhealy1** [comment]
You make a good point.

**Comment by jonhealy1** [comment]
cdn.staclint.com is only be used for older versions of stac: https://github.com/stac-utils/stac-validator/blob/41afba7ec7aae3264f0b7b30dc91e18f423905fa/stac_validator/utilities.py#L133-L147
